using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Resources;
using DevExpress.Internal;
//[assembly: ComVisible(false)]
[assembly: AssemblyTitle(AssemblyInfo.SRAssemblySchedulerWeb)]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany(AssemblyInfo.AssemblyCompany)]
[assembly: AssemblyCopyright(AssemblyInfo.AssemblyCopyright)]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion(AssemblyInfo.SatelliteContractVersion)]
