using System;
using System.Reflection;
using System.Security;
using DevExpress.Internal;
[assembly: AssemblyTitle("DevExpress.Charts.Designer")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion(AssemblyInfo.SatelliteContractVersion)]
[assembly: AllowPartiallyTrustedCallers()]
