@echo off
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

set QTDIR=D:\occt-3rdparty\qt482-vc10-32
echo -- QTDIR set to D:\occt-3rdparty\qt482-vc10-32
set PATH=D:\occt-3rdparty\qt482-vc10-32\bin;%PATH%
echo -- Added D:\occt-3rdparty\qt482-vc10-32\bin to PATH
set QMAKESPEC=win32-msvc2010
echo -- QMAKESPEC set to "win32-msvc2010"

if not "%1"=="vsvars" goto ENDVSVARS
call "D:\DevTools\VStudio\VC10\VC\vcvarsall.bat" x86
:ENDVSVARS

if not "%1"=="vsstart" goto ENDVSSTART
call "D:\DevTools\VStudio\VC10\VC\vcvarsall.bat" x86
devenv /useenv
:ENDVSSTART

